title: Site

deletable: false
pages: false
create: false

tabs:
  content:
    label: Content
    columns:
      - width: 1/2
        sections:
          pages:
            type: pages
            create: gallery
            templates:
              - bio
              - merch
              - gallery
              - shows
              - contact
            options:
              create: false
              pages: false
              deletable: false
              changeStatus: false
              changeTemplate: false
              duplicate: false
              changeSlug: false        
  style:
    label: Style Settings
    fields:
        projectcolor:
          label: Color
          type:  text
          help: |
            x
          width: 1/3
       info:
          type: info
          width: 1/3
          label: Color palette
          text: |
            color - #

  policy:
    label: Policy and Imprint
  error:
    label: Error message
